np-wp:
  build: .
  dockerfile: Dockerfile
  links:
  - np-wpdb:mysql
  ports:
  - 80:80
  volumes:
  - ./wp_html:/var/www/html
  - './tools:/tools' 
  environment: 
    VOLUME: '/var/www/html'
    DOCKER_USER: 'www-data'
    DOCKER_GROUP: 'www-data'
    HOST_USER_ID: 1001
    HOST_GROUP_ID: 1001
    SITE_NAME: test
    WP_USER: nodopiano
    WP_PASSWORD: nodopiano
np-wpdb:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes:
  - ./db/:/var/lib/mysql
np-wpmy:
  image: corbinu/docker-phpmyadmin
  links:
    - np-wpdb:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: root
