version: '3'
services:
  kwp:
    image: kayak:composer
    build:
      context: ./
      dockerfile: /docker/Dockerfile
      args:
        HOST_GUID: ${UID}
    ports:
    - 80:80
    volumes:
    # - ./themes:/var/www/html/wp/wp-content/themes
    - ./:/var/www/html/
    - './docker/tools:/tools' 
    env_file: ./.env
    networks:
      - wordpress
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  kdb:
    image: mariadb
    env_file: ./.env
    ports:
    - 3306:3306
    volumes:
    - wordpressmysql:/var/lib/mysql
    networks:
      - wordpress
  kmy:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    networks:
      - wordpress
    env_file: ./.env
  kredis:
    image: redis:alpine
    networks:
      - wordpress
    env_file: ./.env
networks:
  wordpress:
    driver: "bridge"
volumes:
  wordpressmysql:
    driver: "local"
