version: '2'
services:
  np-wp:
    build:
      context: ./docker
      dockerfile: Dockerfile
    links:
    - np-wpdb:mysql
    ports:
    - 80:80
    volumes:
    - ./wp_html:/var/www/html
    - './docker/tools:/tools' 
    environment: 
      VOLUME: '/var/www/html'
      SITE_NAME: "${SITE_NAME}"
      SITE_URL: "${SITE_URL}"
      WP_EMAIL: "${WP_EMAIL}"
      WP_USER: "${WP_USER}"
      WP_PASSWORD: "${WP_PASSWORD}"
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
    networks:
      - wordpress
  np-wpdb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      MYSQL_DATABASE: "${WORDPRESS_DB_NAME}"
      MYSQL_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      MYSQL_USER: "${WORDPRESS_DB_USER}"
    volumes:
    - wordpressmysql:/var/lib/mysql
    networks:
      - wordpress
  np-wpmy:
    image: corbinu/docker-phpmyadmin
    links:
      - np-wpdb:mysql
    ports:
      - 8181:80
    networks:
      - wordpress
    environment:
      MYSQL_USERNAME: "${WORDPRESS_DB_USER}"
      MYSQL_ROOT_PASSWORD: "{WORDPRESS_DB_PASSWORD}"
networks:
  wordpress:
    driver: "bridge"
volumes:
  wordpressmysql:
    driver: "local"
